# Generated by Django 5.0.4 on 2024-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
